"""
Train NNUE on 50K random games data generated by Rust.

Usage:
    uv run python examples/train_nnue_random.py
"""

import os, sys, time, struct, json
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

from penguinchess.ai.nnue import NNUE, HIDDEN_DIM
from penguinchess.ai.sparse_features import DENSE_DIM


def load_binary_data(path: str, max_samples: int = None):
    """Load Rust-generated binary NNUE training data."""
    raw = np.fromfile(path, dtype=np.uint8)
    count = int.from_bytes(raw[:8].tobytes(), 'little')
    if max_samples:
        count = min(count, max_samples)
    records = raw[8:8 + count * 292].reshape(-1, 292)

    # Parse sparse (6 × int32 at offset 0)
    sparse_raw = records[:, 0:24].view(np.int32).reshape(-1, 6)
    # Parse dense (66 × float32 at offset 24)
    dense_raw = records[:, 24:24 + 66 * 4].view(np.float32).reshape(-1, 66)
    # Parse outcome (float32 at offset 24+66*4 = 288)
    outcome_raw = records[:, 288:292].view(np.float32).flatten()

    # Build sparse list (filter -1 padding)
    sparse_list = []
    for row in sparse_raw:
        sparse_list.append([int(x) for x in row if x >= 0])

    return sparse_list, dense_raw, outcome_raw, count


class RandomNNUEDataset(Dataset):
    def __init__(self, sparse, dense, values):
        # Convert sparse to fixed-size (N, 6) array, padded with -1
        self.sparse_np = np.full((len(sparse), 6), -1, dtype=np.int32)
        for i, s in enumerate(sparse):
            for j, v in enumerate(s):
                if j >= 6: break
                self.sparse_np[i, j] = np.int32(v)
        self.dense = torch.from_numpy(dense.copy())
        self.values = torch.from_numpy(values.copy())

    def __len__(self):
        return len(self.values)

    def __getitem__(self, idx):
        # Return sparse as list of ints (filtering -1)
        sparse_row = [int(x) for x in self.sparse_np[idx] if x >= 0]
        return sparse_row, self.dense[idx], self.values[idx], 0


def collate(batch):
    sb = [b[0] for b in batch]
    db = torch.stack([b[1] for b in batch])
    vb = torch.stack([b[2] for b in batch])
    stm = [0] * len(batch)
    return sb, db, vb, stm


def main():
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f'Device: {device}')

    # Load data (50K for fast training turnaround)
    data_path = Path(__file__).parent.parent / 'backend_data' / 'nnue_random_50k.bin'
    print(f'Loading {data_path}...')
    t0 = time.time()
    sparse, dense, values, count = load_binary_data(str(data_path), max_samples=55000)
    print(f'  {len(sparse)} positions, {time.time()-t0:.0f}s')

    split = 50000
    train_ds = RandomNNUEDataset(sparse[:split], dense[:split], values[:split])
    val_ds = RandomNNUEDataset(sparse[split:], dense[split:], values[split:])

    train_loader = DataLoader(train_ds, batch_size=4096, shuffle=True, collate_fn=collate, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=4096, shuffle=False, collate_fn=collate, num_workers=0)

    # Model
    model = NNUE().to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3)
    criterion = nn.MSELoss()

    best_val = float('inf')
    best_state = None
    epochs = 30

    print(f'Training {epochs} epochs...')
    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for sb, db, vb, stm_b in train_loader:
            db, vb = db.to(device), vb.to(device)
            pred = model(sb, db, stm_players=stm_b)
            loss = criterion(pred, vb)
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            train_loss += loss.item() * len(vb)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for sb, db, vb, stm_b in val_loader:
                db, vb = db.to(device), vb.to(device)
                pred = model(sb, db, stm_players=stm_b)
                val_loss += criterion(pred, vb).item() * len(vb)

        train_loss /= len(train_ds)
        val_loss /= len(val_ds)
        scheduler.step(val_loss)

        if val_loss < best_val:
            best_val = val_loss
            best_state = model.state_dict().copy()

        lr_now = optimizer.param_groups[0]['lr']
        print(f'  epoch {epoch+1:>2d}/{epochs}  train={train_loss:.4f}  val={val_loss:.4f}  LR={lr_now:.1e}')

    # Save best model
    model.load_state_dict(best_state)
    out_path = Path(__file__).parent.parent / 'models' / 'nnue' / 'nnue_random.pt'
    out_path.parent.mkdir(parents=True, exist_ok=True)
    torch.save({'model_state': best_state, 'val_loss': best_val}, str(out_path))
    print(f'\nSaved: {out_path} (val_loss={best_val:.4f})')

    # Quick eval vs random via Rust AB search
    print('\nEval vs Random (Rust AB depth 2, 50 games)...')
    from penguinchess.rust_ffi import ffi_ab_create
    handle = ffi_ab_create(json.dumps({'max_depth':2,'time_limit_ms':0,'tt_size':262144,'lmr_moves':3,'lmr_depth':1}))
    handle.set_weights(model.state_dict())

    from penguinchess.core import PenguinChessCore
    wins = 0; draws = 0; losses = 0
    for g in range(50):
        core = PenguinChessCore(seed=g*1000).reset(seed=g*1000)
        while True:
            legal = core.get_legal_actions()
            if not legal: break
            if core.current_player == 0:
                # NNUE agent (player 0)
                import json as j
                smap = {'active':'active','occupied':'occupied','used':'used','eliminated':'eliminated'}
                hexes = [{'coord':{'q':h.q,'r':h.r,'s':h.s},'state':smap.get(h.state,'active'),'points':h.points if h.state=='active' else 0} for h in core.hexes]
                pieces = [{'id':p.id,'alive':p.alive,'hex_idx':core.hexes.index(p.hex) if p.alive and p.hex else None,'hex_value':p.hex_value} for p in core.pieces]
                state_json = j.dumps({'board':{'cells':hexes,'hex_map':{},'neighbors':[]},'pieces':pieces,'scores':core.players_scores,'phase':'placement' if core.phase=='placement' else 'movement','current_player':0,'placement_count':core._placement_count,'episode_steps':core._episode_steps,'terminated':False,'last_action':None})
                result = handle.search(state_json, max_depth=2)
                action = result.get('best_action', legal[0])
            else:
                # Random (player 1)
                action = legal[np.random.randint(len(legal))]
            core.step(action)
            if core.phase == 'gameover': break
        s1, s2 = core.players_scores
        if s1 > s2: wins += 1
        elif s2 > s1: losses += 1
        else: draws += 1
        if (g+1) % 25 == 0: print(f'  [{g+1}/50] W{wins} L{losses} D{draws}')

    print(f'Result: {wins/50:.0%} win, {draws/50:.0%} draw, {losses/50:.0%} loss')
    handle.free()


if __name__ == '__main__':
    main()
